function Fg = autoGen_Fg(u1,u2,u3,u4,u5)
%AUTOGEN_FG
%    FG = AUTOGEN_FG(U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Apr-2018 20:01:44

_assign(Fg,reshape([-1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,-1.0],[5,5]));
